/** Use single-select filters for mutually exclusive scopes and multi-select menus when values can be combined. */
import * as React from 'react';
import { Check, ChevronDown, RotateCcw } from 'lucide-react';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

export interface FilterOption<T extends string> { value: T; label: string; count?: number; disabled?: boolean; }
export function FilterBadge({ count }: { count: number }) { return <span className="inline-flex min-w-5 items-center justify-center rounded-full bg-accent-soft px-1.5 py-0.5 text-meta font-semibold tabular-nums text-accent">{count}</span>; }
export function FilterReset({ onClick, className }: { onClick: () => void; className?: string }) { return <Button variant="ghost" size="sm" onClick={onClick} className={cn('gap-1.5', className)}><RotateCcw className="h-3.5 w-3.5" aria-hidden="true" />Reset</Button>; }
export function SingleSelectFilter<T extends string>({ label, options, value, onValueChange, className }: { label: string; options: readonly FilterOption<T>[]; value: T; onValueChange: (value: T) => void; className?: string }) {
  const id = React.useId();
  const refs = React.useRef<Array<HTMLButtonElement | null>>([]);
  const moveFocus = (currentIndex: number, direction: number) => {
    const enabled = options.map((option, index) => ({ option, index })).filter(({ option }) => !option.disabled);
    const enabledIndex = enabled.findIndex(({ index }) => index === currentIndex);
    if (enabledIndex < 0 || enabled.length === 0) return;
    refs.current[enabled[(enabledIndex + direction + enabled.length) % enabled.length].index]?.focus();
  };
  return <div role="radiogroup" aria-label={label} className={cn('inline-flex items-center gap-1 rounded-xl bg-surface p-1', className)}>{options.map((option, index) => { const selected = option.value === value; return <button ref={(element) => { refs.current[index] = element; }} key={option.value} type="button" role="radio" aria-checked={selected} tabIndex={selected ? 0 : -1} disabled={option.disabled} onClick={() => onValueChange(option.value)} onKeyDown={(event) => { if (event.key === 'ArrowRight' || event.key === 'ArrowDown') { event.preventDefault(); moveFocus(index, 1); } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') { event.preventDefault(); moveFocus(index, -1); } else if (event.key === 'Home') { event.preventDefault(); refs.current.find((item) => item && !item.disabled)?.focus(); } else if (event.key === 'End') { event.preventDefault(); [...refs.current].reverse().find((item) => item && !item.disabled)?.focus(); } }} className={cn('relative z-0 inline-flex items-center gap-2 rounded-lg px-3.5 py-2 text-body-sm font-semibold transition-colors duration-150 ease-swift focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-ring focus-visible:ring-offset-2 focus-visible:ring-offset-app disabled:pointer-events-none disabled:opacity-50', selected ? 'text-primary' : 'text-secondary hover:text-primary')}>
    {selected && <motion.span layoutId={`${id}-filter`} className="absolute inset-0 -z-10 rounded-lg bg-app shadow-sm" transition={{ duration: 0.18, ease: [0.23, 1, 0.32, 1] }} />}<span>{option.label}</span>{option.count !== undefined && <FilterBadge count={option.count} />}
  </button>; })}</div>;
}
export function MultiSelectFilter<T extends string>({ label, options, value, onValueChange, onReset, className }: { label: string; options: readonly FilterOption<T>[]; value: readonly T[]; onValueChange: (value: T[]) => void; onReset?: () => void; className?: string }) {
  const [open, setOpen] = React.useState(false); const rootRef = React.useRef<HTMLDivElement>(null); const triggerRef = React.useRef<HTMLButtonElement>(null); const itemRefs = React.useRef<Array<HTMLButtonElement | null>>([]); const listId = React.useId(); const selected = options.filter((option) => value.includes(option.value));
  React.useEffect(() => { const close = (event: PointerEvent) => { if (rootRef.current && !rootRef.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close); }, []);
  const toggle = (item: T) => onValueChange(value.includes(item) ? value.filter((value) => value !== item) : [...value, item]);
  const focus = (index: number, direction: number) => { const enabled = options.map((option, index) => ({ option, index })).filter(({ option }) => !option.disabled); const current = enabled.findIndex((item) => item.index === index); if (current >= 0 && enabled.length) itemRefs.current[enabled[(current + direction + enabled.length) % enabled.length].index]?.focus(); };
  const onItemKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>, index: number, item: T) => { if (event.key === 'Escape') { event.preventDefault(); setOpen(false); triggerRef.current?.focus(); } else if (event.key === 'ArrowDown') { event.preventDefault(); focus(index, 1); } else if (event.key === 'ArrowUp') { event.preventDefault(); focus(index, -1); } else if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); toggle(item); } };
  return <div ref={rootRef} className={cn('relative inline-flex items-center gap-2', className)}><button ref={triggerRef} type="button" aria-haspopup="listbox" aria-controls={listId} aria-expanded={open} onClick={() => setOpen((current) => !current)} onKeyDown={(event) => { if (event.key === 'Escape') setOpen(false); if ((event.key === 'ArrowDown' || event.key === 'Enter' || event.key === ' ') && !open) { event.preventDefault(); setOpen(true); window.requestAnimationFrame(() => itemRefs.current.find(Boolean)?.focus()); } }} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-subtle bg-app px-3 text-body-sm font-semibold text-primary transition-colors duration-150 ease-swift hover:bg-surface-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-ring focus-visible:ring-offset-2 focus-visible:ring-offset-app"><span className="text-secondary">{label}</span>{selected.length ? <span className="flex max-w-56 items-center gap-1 overflow-hidden">{selected.slice(0, 2).map((item) => <span key={item.value} className="truncate rounded-md bg-accent-soft px-2 py-0.5 text-meta font-semibold text-accent">{item.label}</span>)}{selected.length > 2 && <FilterBadge count={selected.length} />}</span> : <span className="text-muted">Select filters</span>}<ChevronDown className={cn('h-4 w-4 text-muted transition-transform duration-150 ease-swift', open && 'rotate-180')} aria-hidden="true" /></button>{value.length > 0 && onReset && <FilterReset onClick={onReset} />}{open && <div id={listId} role="listbox" aria-label={label} aria-multiselectable="true" className="absolute left-0 top-full z-30 mt-2 min-w-64 rounded-xl border border-subtle bg-app p-1.5 shadow-pop">{options.map((option, index) => { const checked = value.includes(option.value); return <button key={option.value} ref={(element) => { itemRefs.current[index] = element; }} type="button" role="option" aria-selected={checked} disabled={option.disabled} onClick={() => toggle(option.value)} onKeyDown={(event) => onItemKeyDown(event, index, option.value)} className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-body-sm text-secondary transition-colors duration-150 ease-swift hover:bg-surface-hover hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-ring disabled:pointer-events-none disabled:opacity-50"><span className={cn('flex h-4 w-4 items-center justify-center rounded border', checked ? 'border-accent bg-accent text-on-accent' : 'border-medium bg-app')} aria-hidden="true">{checked && <Check className="h-3 w-3" />}</span><span className="flex-1">{option.label}</span>{option.count !== undefined && <span className="text-meta tabular-nums text-muted">{option.count}</span>}</button>; })}</div>}</div>;
}
